apiVersion: v2
appVersion: "1.1.1"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 1.1.1
deprecated: false
description: testing stuff
home: https://github.com/truecharts/apps/tree/master/charts/stable/teamspeak3
icon: https://truecharts.org/_static/img/appicons/teamspeak3.png
keywords:
- test
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: teamcitymeetsaosp
sources:
- https://hub.docker.com/jetbrains/teamcity-agent
type: application
version: 1.1.1
annotations:
  truecharts.org/catagories: |
    - test
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
